sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tB4rdwKGzwVJzdNMFiZ
    access-key-secret: 8BhMV6AAQq0XwVJPwXOWDA4IT1YJZq
    bucket-name: sky-pwd
  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 1
    max-active: 10
    max-idle: 10
    min-idle: 1
    time-between-eviction-runs: 10s
  wechat:
    appid: wx2461097ae4ee1aab
    secret: 8b3ec1c01abc6620ed71f9c2d97b116d
    mchid: 1649629874
    mchSerialNo: 6A38F167B49601220CC9B124DC5F44D6BA0AAFD0
    privateKeyFilePath: C:\Users\D\WXCertUtil\WXCertUtil\cert\1649629874_20230727_cert\apiclient_key.pem
    apiV3Key: fsdg468asdf3ht4r843fASGFR5D5ASF6
    weChatPayCertFilePath: C:\Users\D\WXCertUtil\WXCertUtil\pingtai\wechatpay_1A6427513DB5CDB77490DD404E5C1B88010B5F94.pem
    notifyUrl: https://10897ff7.r9.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://10897ff7.r9.cpolar.top/notify/refundSuccess

