sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tB4rdwKGzwVJzdNMFiZ
    access-key-secret: 8BhMV6AAQq0XwVJPwXOWDA4IT1YJZq
    bucket-name: sky-pwd
